### ISSUE TITLE
error when adding user 

### ISSUE THREAD

**Issue by MartinSchobben** [irods/irods_demo#56]
Using icommands to add an user fails but sometimes recreating the containers removes the problem.

```
docker exec irods_demo-irods-client-icommands-1  iadmin mkuser alice rodsuser
```
Output:

```
remote addresses: 172.28.0.3 ERROR: rcGeneralAdmin failed with error -1213000 RE_UNABLE_TO_READ_SESSION_VAR 
Level 0: DEBUG: error: unable to read session variable $rodsZoneProxy.
line 23, col 27, rule base core
  acCreateCollByAdmin("/"++$rodsZoneProxy++"/home", $otherUserName);
                           ^

==========
error: unable to read session variable $otherUserName.
line 13, col 4, rule base core
 ON($otherUserName == "anonymous") {
```

The same seems to happen with the HTTP API.

```
irods_response.status_code: -1213000
irods_response.status_message: RE_UNABLE_TO_READ_SESSION_VAR: Failed to add user [Alice].
```

**Comment by alanking** [comment]
Are you seeing this consistently? You said "sometimes" but just curious how frequently this occurs.

We have seen this issue in testing due to an issue which is still under ongoing investigation: https://github.com/irods/irods/issues/6954

You will either need to tear down the zone and start over when this happens or, if you'd like to keep the zone and be a bit more surgical, you need to stop the iRODS server, clear out `/dev/shm` of any files starting with `irods_*`, and start the server again. Things should return to normal after that.

**Comment by MartinSchobben** [comment]
In the process of developing/debugging rirods (R client) I often `docker compose up` and `docker compose down` the irods_demo to test new features and run unit tests. It is often enough that it interferes with my development efforts, so it is definitely pretty consistently showing up. I can't really put a number on it.

**Comment by MartinSchobben** [comment]
I do need to add one detail here. As I ship the `irods_demo` with rirods to the CRAN servers I reduce the size of the directory by using the following `Makefile` :

https://github.com/MartinSchobben/irods_client_library_rirods/blob/dev/dev/Makefile

Stripping irods_demo down to the minimum for testing and showcasing rirods functionality.

**Comment by alanking** [comment]
Okay, thanks for the information. You may wish to play around with the size of shared memory in the container by modifying the YAML file. This won't fix the issue but may make it less common.

If you happen to notice this again, can you share the server logs if they are available? It could provide some clues as to whether it is truly related to the other issue we are looking into.

**Comment by MartinSchobben** [comment]
I tried to increase shared memory of the irods-catalog-provider` in yaml file, like so:

```
    irods-catalog-provider:
        build:
            context: irods_catalog_provider
            shm_size: '2gb'
```
I also noted this error while running the containers with increased shared memory size.

```
irods-catalog-provider-1  | {"log_category":"legacy","log_level":"error","log_message":"prepareServerSharedMemory: failed to prepare shared memory. Exception caught [No space left on device]","server_host":"f3bd42e2ca4a","server_pid":145,"server_timestamp":"2024-01-24T07:04:17.306Z","server_type":"agent","server_zone":"tempZone"}
```

**Comment by trel** [comment]
note the difference in `irods-catalog-provider.build.shm_size` (for building) and `irods-catalog-provider.shm_size` (for running).

the default is 64mb, so you could try 'just' 500mb and that may prove sufficient.

**Comment by MartinSchobben** [comment]
That seems to do the trick.

**Comment by MartinSchobben** [comment]
I change the docker compose yaml. This is just a fragment of the whole yaml:

```
    irods-catalog-provider:
        build:
            context: irods_catalog_provider
        shm_size: "500mb"
        healthcheck:
            test: ["CMD", "su", "-", "irods", "-c", "ils || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 3
            start_period: 20s
            start_interval: 2s
        depends_on:
            - irods-catalog
  ```
